# Generated by Django 2.2.2 on 2019-07-03 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.BigIntegerField(unique=True),
        ),
    ]
